alias b := build
alias c := check
alias t := test


default:
  @just --list

# run and restart on changes
watch:
  env RUST_LOG=${RUST_LOG:-debug} cargo watch -x run
  
# run `cargo build` on everything
build:
  cargo build --workspace --all-targets

# run `cargo check` on everything
check:
  cargo check --workspace --all-targets

# run tests
test: build
  cargo test

# run lints (git pre-commit hook)
lint:
  env NO_STASH=true $(git rev-parse --git-common-dir)/hooks/pre-commit

# run all checks recommended before opening a PR
final-check: lint
  cargo test --doc
  just test

# run code formatters
format:
  cargo fmt --all
  nixpkgs-fmt $(echo **.nix)
