{
  pkgs,
  mkLib,
}:
let
  inherit (pkgs) lib;
  inherit (lib) assertMsg;
  timer = pkgs.callPackage ../lib/pkgs/git-hook-check-timer.nix { };
  fakeAstGrep = pkgs.writeShellScriptBin "ast-grep" ''
    printf '%s\n' "$*" >> "$AST_GREP_LOG"
  '';

  defaultLib = mkLib pkgs { };
  disabledLib = mkLib pkgs {
    config.ast-grep.enable = false;
  };
  justDisabledLib = mkLib pkgs {
    config.ast-grep.just.enable = false;
  };
  preCommitDisabledLib = mkLib pkgs {
    config.ast-grep.pre-commit.enable = false;
  };
  configuredLib = mkLib pkgs {
    config = {
      ast-grep = {
        package = fakeAstGrep;
        configFile = ".config/ast-grep/sgconfig.yml";
        pre-commit.args = [
          "--error=complex-conditional"
          "--filter"
          "rust-.*"
        ];
      };
      cargo.pre-commit.cargo-lock.enable = false;
      git.pre-commit = {
        trailing_newline = false;
        trailing_whitespace = false;
      };
      semgrep.enable = false;
      shellcheck.enable = false;
      treefmt.enable = false;
      typos.enable = false;
    };
  };
in
assert assertMsg defaultLib.config.ast-grep.enable "ast-grep is enabled by default";
assert assertMsg defaultLib.config.ast-grep.just.enable
  "ast-grep just recipe is enabled by default";
assert assertMsg defaultLib.config.ast-grep.pre-commit.enable
  "ast-grep pre-commit hook is enabled by default";
assert assertMsg (builtins.hasAttr "ast-grep" defaultLib.config.just.rules)
  "ast-grep just recipe is generated by default";
assert assertMsg (builtins.hasAttr "ast_grep" defaultLib.config.git.pre-commit.hooks)
  "ast-grep pre-commit hook is generated by default";
assert assertMsg (lib.elem pkgs.ast-grep defaultLib.config.env.shellPackages)
  "ast-grep package is added to development shells";
assert assertMsg (
  !(builtins.hasAttr "ast-grep" disabledLib.config.just.rules)
) "top-level disable removes the ast-grep just recipe";
assert assertMsg (
  !(builtins.hasAttr "ast_grep" disabledLib.config.git.pre-commit.hooks)
) "top-level disable removes the ast-grep pre-commit hook";
assert assertMsg (
  !(lib.elem pkgs.ast-grep disabledLib.config.env.shellPackages)
) "top-level disable removes the ast-grep package";
assert assertMsg (
  !(builtins.hasAttr "ast-grep" justDisabledLib.config.just.rules)
) "just disable removes only the ast-grep just recipe";
assert assertMsg (builtins.hasAttr "ast_grep" justDisabledLib.config.git.pre-commit.hooks)
  "just disable preserves the ast-grep pre-commit hook";
assert assertMsg (
  !(builtins.hasAttr "ast_grep" preCommitDisabledLib.config.git.pre-commit.hooks)
) "pre-commit disable removes only the ast-grep hook";
assert assertMsg (builtins.hasAttr "ast-grep" preCommitDisabledLib.config.just.rules)
  "pre-commit disable preserves the ast-grep just recipe";
assert assertMsg (lib.elem fakeAstGrep configuredLib.config.env.shellPackages)
  "a custom ast-grep package replaces the default package";
assert assertMsg (
  !(lib.elem pkgs.ast-grep configuredLib.config.env.shellPackages)
) "a custom ast-grep package removes the default package";
assert assertMsg
  (lib.hasInfix "--config .config/ast-grep/sgconfig.yml" configuredLib.config.just.rules.ast-grep.content)
  "custom config path is rendered into the just recipe";
assert assertMsg
  (lib.hasInfix "'--error=complex-conditional' --filter 'rust-.*'" configuredLib.config.git.pre-commit.hooks.ast_grep)
  "pre-commit arguments are shell escaped and rendered into the hook";
pkgs.runCommand "ast-grep-module-tests"
  {
    nativeBuildInputs = [
      fakeAstGrep
      pkgs.bash
      pkgs.coreutils
      pkgs.git
      pkgs.gnugrep
      pkgs.parallel
      timer
    ];
  }
  ''
    set -euo pipefail

    mkdir repo
    cd repo
    git init -q
    touch tracked
    git add tracked

    export AST_GREP_LOG="$PWD/ast-grep.log"
    pre_commit="${configuredLib.root}/misc/git-hooks/pre-commit"

    NO_STASH=1 bash "$pre_commit"
    [ ! -e "$AST_GREP_LOG" ]

    mkdir -p .config/ast-grep
    touch .config/ast-grep/sgconfig.yml
    NO_STASH=1 bash "$pre_commit"
    [ ! -e "$AST_GREP_LOG" ]

    printf 'ruleDirs: []\n' > .config/ast-grep/sgconfig.yml
    NO_STASH=1 bash "$pre_commit"
    printf '%s\n' \
      "scan --config .config/ast-grep/sgconfig.yml --error=complex-conditional --filter rust-.*" \
      > expected.log
    cmp expected.log "$AST_GREP_LOG"

    touch "$out"
  ''
